import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import NextTopLoader from 'nextjs-toploader';
import { PreloadHomePageResources } from '@/lib/preload-resources';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <NextTopLoader showSpinner={false} color='#4CAF50' />
        <PreloadHomePageResources />
        {children}
      </body>
    </html>
  );
}
