import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { CSSProperties } from "react";
import Header from "@/components/auth/header";
import NextTopLoader from "nextjs-toploader";
import { PreloadAuthPageResources } from "@/lib/preload-resources";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const styles: CSSProperties = {
  backgroundImage: `linear-gradient(rgba(0,0,0,0.25), rgba(0,0,0,0.25)), url('/authbg.svg')`,
  backgroundRepeat: "no-repeat",
  backgroundPosition: "center",
  backgroundSize: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NextTopLoader showSpinner={false} color="#4CAF50" />
        <PreloadAuthPageResources />
        <main style={styles} className="grid min-h-screen grid-rows-[auto_1fr]">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
