import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import NextTopLoader from 'nextjs-toploader';
import Sidebar from '@/components/account/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <NextTopLoader showSpinner={false} color='#4CAF50' />
        <section className='lg:grid lg:grid-cols-[240px_1fr]'>
          <Sidebar />
          <main>{children}</main>
        </section>
      </body>
    </html>
  );
}
